### ISSUE TITLE
Import=Adding OR replacing existing Bookmarks?

### ISSUE THREAD

**Issue by bsto** [moritz-h/urls-list#1]
It does not become clear if "adding bookmarks " mean just add the imported URLs to the existing bookmarks or to replace them completely.

The AddOn should offer both methods

**Comment by moritz-h** [comment]
I don't know where you saw the "adding bookmarks", this Add-on does not interact with bookmarks at all. It only interacts with the opened tabs.

If you paste a list of urls (one per line) into the textfield and click open, each url is opened in a new tab.
Your currently opened tabs are not changed in any way, just new tabs are opened.
(When urls are already opened in an existing tab, they are ignored and no new tab is opened for this urls.)

Please give more informations what you mean with "adding bookmarks".
