### ISSUE TITLE
[Feature request] Automatically save list of URLs of open tabs

### ISSUE THREAD

**Issue by rieje** [moritz-h/urls-list#10]
This simple add-on is really awesome for heavy tab users--I use it to quickly transfer Firefox "sessions" in a fool-proof manner. 

A really useful feature would be if the add-on could write to a file the list of URLs and do so either in a set interval (e.g. every 5 minutes) or every time a new URL is visited or removed from the tabs. Even better is if it can feed this list for Firefox to open when it starts.

I haven't found an elegant solution to saving/ restoring Firefox sessions in a fool-proof manner (I current backup sessionstore.js periodically but since the file is only created after Firefox is terminated, if Firefox crashes then you lose the most recent session and can only restore the session before this most recent session).

Hope it's something that can be considered--what I've described might be overly complicated but anything that can achieve something similar would be really useful.

**Comment by moritz-h** [comment]
I think this feature is not possible.

First of all restoring the currently open tabs is a out of the box feature of Firefox.
Go to settings and the very first option is `When Firefox starts:`, select `Show my windows and tabs from last time`. (Does not work when you delete history on closing Firefox.)
Also when Firefox crashes there is normally an restore option on the next start.

Furthermore it seem (on a quick look) technically not possible to write files in the background with the WebExtension Plugin API. You can only open a save file dialog. (For security and privacy I also think it is a good choice, that a plugin cannot read or write files directly without user interaction.)
So it is not possible to automatically write files. The only option would be to save data within the Firefox storage. But then for me there is no much difference to the history of Firefox itselfs.

(A save to file button, which opens a save file dialog, is already added to this plugin in master branch, see #9 . I need to release a new version to make this available.)

Closing for now as  automatically writing to file seems not possible. But please comment if you think there is an other option on how to do this.

**Comment by moritz-h** [comment]
@rieje Perhaps this addon works for you: https://addons.mozilla.org/en-US/firefox/addon/tab-session-manager/
(I don't have tested it, just remembered me on this issue :smile: )

**Comment by raywood1** [comment]
I echo the feature request. Since the effective demise of Session Manager, I have not been able to find a reliable tool to perform automatic backups of open tabs.

Unfortunately, the recommended add-on (Tab Session Manager) does not have a good rating. I think I may have already tried it. I also just tried MySessions. It may prove that automatic saving is possible. Its problem is just that it is not reliable.
