### ISSUE TITLE
Firefox 57 popup menu action can't write into clipboard

### ISSUE THREAD

**Issue by mnba** [moritz-h/urls-list#15]
While clicking on (active, any) tab and selecting in the popup menu the lowest menu item "Copy URLs (All tabs)"
Firefox 57 show error messagebox: 
"Error!
Cannot write to clipboard on settings tab!"

And browser console prints:
Failed to copy text: Error: An unexpected error occurred background.js:47:9

Did this work in previous versions?

**Comment by moritz-h** [comment]
Do you mean the menu when you do right click on the tab? (BTW: That is called context menu, popup is the menu shown, when you click the "UL" button)

Firefox does not allow to copy the tab urls from context menu while a protected site is active for security reasons. Therefore this plugin shows the Error message you see.
A protected site is for example everything that starts with `about:`, the empty new tab page or `addons.mozilla.org`.
And active means the tab you are currently viewing, not the tab where you do the rightclick on. For example while you look at `about:preferences` you cannot do any copy with with the context menu. Please use the "UL" button popup in this case. This works every time.

Can you please retry while for example the github page is active? If the error still happens, can you please provide more Information. What OS/version are you using? Can you copy the url of the currently active tab while this error is shown?

**Comment by mnba** [comment]
Seems this was somewhat related to my tweaked extension version, run in Debug mode, without signatures, etc.
The problem disappeared after I signed the addon.
