### ISSUE TITLE
Import+Export possible from cmdline?

### ISSUE THREAD

**Issue by bsto** [moritz-h/urls-list#2]
What I actually need is a way to import resp. export bookmarks from command line.

Something like this:

firefox.exe -import=D:\browser\urls\myurls.txt

Can the AddOn be extended to support such imports?

**Comment by moritz-h** [comment]
As far as I see it is not possible to read command line arguments within a Firefox Add-on. At least it is not with WebExtensions: https://developer.mozilla.org/en-US/Add-ons/WebExtensions

With this Add-on you can open your myurls.txt manually and copy paste the content to the plugin popup and then open all urls in individual tabs.

Firefox has a command line option to open multiple urls, perhaps you can use a shellscript to read your file and open the urls with firefox. Perhaps this can help:
https://askubuntu.com/questions/617933/open-multiple-firefox-tabs-from-command-line
