### ISSUE TITLE
[Feature request] native messaging

### ISSUE THREAD

**Issue by sharethewisdom** [moritz-h/urls-list#20]
I'd like an external script to be aware of opened urls. In my case, I want Firefox to only open a local file if it isn't already opened.

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Native_messaging
https://github.com/mdn/webextensions-examples/tree/master/native-messaging

**Comment by moritz-h** [comment]
This out of scope of this addon.
Native messaging needs an external application which defines a native message port, then you can write an addon to use this port. (see https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/connectNative)
You must first write the external application/script and then it would strongly depend on this application how to send the messages. So i think it would be much easier to write an seperate native messaging addon for one concrete external application. This "general purpose" url list addon is the wrong place to define an native messaging interface.
