### ISSUE TITLE
[Feature Request] Dark mode

### ISSUE THREAD

**Issue by lonix1** [moritz-h/urls-list#26]
I'm using ubuntu, with gnome dark mode theme

When firefox is in dark mode, and I click to open the popup, the button texts are so light I can't read them. So basically the extension is unusable.

Please add a dark mode option. Can be toggled on/off for those who want it.

**Comment by moritz-h** [comment]
Implemented in b136c28ad4021863ac767a9444f40c4ea6db7dbe and 01e78a8baaf957bba5d0d9a7b1b07989978ead00.

**Comment by lonix1** [comment]
Strange - it isn't available as an upgrade?

**Comment by moritz-h** [comment]
The new feature is only in the source code within this repo, so far. It will be avaiable when a new version is released. (Will be hopefully not too far in future.)

**Comment by moritz-h** [comment]
It took some very long time, but the new version is released now.
