### ISSUE TITLE
FR: Add content menuitem

### ISSUE THREAD

**Issue by Gitoffthelawn** [moritz-h/urls-list#3]
Looks nice.  Thank you.

Can you add a **tab** context menuitem to perform the copy operation?

**Comment by moritz-h** [comment]
Do you mean a "copy url of this tab" context menu entry or "copy all urls from this window" entry?

**Comment by Gitoffthelawn** [comment]
I mean "copy all urls from this window".

The other could be a little useful, but obviously cut and pasting a single url from the urlbar is quite simple.
