### ISSUE TITLE
Don't exclude existing tabs from being opened

### ISSUE THREAD

**Issue by rieje** [moritz-h/urls-list#31]
Looking at the code, it seems it's intention to exclude existing tabs from being opened from a given list. IMO this should only be an option and the default should be to open tabs in the correct order regardless of existing tabs:

* There is no indication that existing tabs are not opened like the rest of the tabs

* This extension has a simple purpose and UI and I don't think it's a good idea to make the default behavior unexpected and different from the expected (advertised?) behavior of simply loading all tabs in the order it was listed. Instead, the current behavior should be an option and not the default.

For my purposes, I have a lot of tabs opened and want to open a list of tabs together for context. Currently, this extension excludes opening tabs of urls I have already opened somewhere in my long list of tabs and I must hunt them down and move them to the correct position in the rest of the list of tabs that was opened. As you can imagine, this is frustrating.

**Comment by moritz-h** [comment]
Adding an option is a good idea. Implemented in fbc9b0907800823c7460342aef803dd109af10eb.

However, I would be in favor of keeping the current default. If it is expected or not probably depdends on the use case. I was highly annoyed by the duplicated tabs, that is the reason why this feature is implemented that way. I understand your argument and there are probably good reasons for both sides, but then I will strongly favor the existing solution to avoid breaking changes in the behavior of the plugin. That may be even more unexpected for existing users. Nevertheless, the option is now there in will be included with the next release.

**Comment by rieje** [comment]
Is it possible you can introduce latest release given that the extension is feature complete with infrequent updates? Thank you for your work.

**Comment by moritz-h** [comment]
It took some very long time, but the new version is released now.
