### ISSUE TITLE
Request: Filters

### ISSUE THREAD

**Issue by rayman89** [moritz-h/urls-list#4]
Could you add options for the people that have a ton of tabs open and only wants only to copy some of the urls?

For example could you add filters to the list to:

* Sort urls by alphabetical order (asc/desc)
* Only show urls from 1 or more domains
* Only show the first/second/third/last quarter of the urls in the list
* Only show urls that link to files that browser opens but not download like  (.jpg .gif .png .pdf .mp3 .mp4 etc)

Thanks for your time and for creating this addon.

**Comment by moritz-h** [comment]
With version 0.3.0 there is a alphabetical sort option. But the other sort options are more complicated. Writing the code for the other options is not the problem, but the UI would be a lot more complicated. Goal of this plugin was to keep it as simple as possible. Do you have an idea how this options should look?

**Comment by rayman89** [comment]
Thanks for implementing the alphabetical order. 

You could add a search bar at the top that filters the urls so typing "youtube" would find in the list those that have "youtube" on the url. Typing ".jpg" would show only urls that have .jpg on their url etc.

Probably this will require to show the urls different than plain text in that case for the user to open links he wants to paste/type you could make it so the button "open" replaces the current "page" the popup is showing and show a new "page" with blank text box with a title indication to paste/type the urls the user wants to open and two buttons below one to open those urls and return you to the initial "page" and an other that says cancel which would only return you to the initial "page".

BTW if you want a cleaner look you could put the Sort A -> Z  button next to the "Url list" title; make the "Sort by" just text and A -> Z to be the label of the button and on press it will sort them that way and change the label and functionality of the button to Z -> A next to that all to the right you could  put the save as button. If you wanna get fancy you could show the A -> Z button like an icon like this 
![imagen](https://user-images.githubusercontent.com/5449042/33153064-d53a2b52-cfd7-11e7-8b4c-f3579cdbd321.png) and the save button as a floppy disk.

Also probably the "reset" button if you implement the suggestion in the way I mentioned could be removed.

**Comment by moritz-h** [comment]
Thanks for the suggestions. I have now added a search textbox, where you can filter the list with a regular expression.

> Probably this will require to show the urls different than plain text in that case for the user to open links he wants to paste/type you could make it so the button "open" replaces the current "page" the popup is showing and show a new "page" with blank text box with a title indication to paste/type the urls the user wants to open and two buttons below one to open those urls and return you to the initial "page" and an other that says cancel which would only return you to the initial "page".

I don't understand what you describe here.

I want to keep the plain textbox, as I see this as the basic concept why I made this AddOn. This should stay as simple as possible. To not mess up input and filters, the textbox is set to read only while any filter is active.

Please try the latest version if this resolves your feature request.

**Comment by rayman89** [comment]
Works great now thanks. The only thing I noticed is that when a filter is active the buttons at the bottom get duplicated.
![imagen](https://user-images.githubusercontent.com/5449042/33216744-1c8c6230-d12d-11e7-86f7-027f97da1ef9.png)

 What you quoted was a suggestion in case you needed to eliminate the editable text box but it wasn't needed so don't mind it.

**Comment by moritz-h** [comment]
Can you please open a seperate issue for the graphics bug to not forget this. This seems very strange, the popup ist just like normal html site, Firefox does the rendering.
Please also write there your OS and Firefox version. With FF57 on Ubuntu everythings looks fine for me.
