### ISSUE TITLE
android support?

### ISSUE THREAD

**Issue by conceptualspace** [moritz-h/urls-list#5]
install is blocked on android: addons page says the extension requires ff v55+ but the mobile app is currently @ v54

**Comment by conceptualspace** [comment]
ah, browseraction is only supported in 55+ (!) at last...
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs

**Comment by moritz-h** [comment]
Yes, this is exactly the reason, why i set minimum version to 55. Installation works on current 54, but it would be useless, because there is no button or menu visible where you can see the URLs.
