### ISSUE TITLE
[Bug] No buttons when action-button is placed in "More Tools..."

### ISSUE THREAD

**Issue by Dezaimasu** [moritz-h/urls-list#8]
Nightly 57.0a1 (2017-09-16) (64-bit)
Buttons "Reset", "Open", "Copy" are unavailable if extension button is placed in "More Tools..." menu.

![image1](https://user-images.githubusercontent.com/1636242/30520157-b22578b6-9bb0-11e7-8c86-4100c65eb7ab.png)
![image2](https://user-images.githubusercontent.com/1636242/30520158-b55c56ee-9bb0-11e7-8fa0-f24640020f16.png)

**Comment by Dezaimasu** [comment]
There's something really wrong in how popus for any extensions acts themselves when opened from "More Tools..." menu. Hope Mozilla will fix it.
Strictly specifying height for body (at least 570px) is probably the simplest fix for this now.

**Comment by moritz-h** [comment]
For the current Firefox 55 everything looks good with the more menu.
If I understand you right this is a general Firefox 57 Bug, so I'm closing this here for now. When there are changes needed for FF57 release I will try to fix them on time.
